addpath('..\..\..\data\01. Pilot-Experiments\');
addpath('..\..\getData\');
addpath('..\..\figures\');
[params] = GetParameters();

load('E:\GitHub\analysis-VR\data\01. Pilot-Experiments\results_pilots.mat');


%%
results.full_offset.Condition1 = params.conditions{1, 1};
results.full_offset.Condition2 = params.conditions{1, 3};

[comparisonResults] = statisticsQuestionnaires (...
    nanmean(squeeze(QuestionnaireData(params.quest.ownership, 1, :))), ...
    nanmean(squeeze(QuestionnaireData(params.quest.ownership, 3, :)))...
    );

results.full_offset.ownership = comparisonResults;

plotQuestionnaires(...
    nanmean(squeeze(QuestionnaireData(params.quest.ownership, 1, :))), ...
    nanmean(squeeze(QuestionnaireData(params.quest.ownership, 3, :))), ...
    'Sense of Ownership', params.conditions{1, 1}, params.conditions{1, 3}, ...
    comparisonResults.stats);

%%
[comparisonResults] = statisticsQuestionnaires (...
    nanmean(squeeze(QuestionnaireData(params.quest.agency, 1, :))), ...
    nanmean(squeeze(QuestionnaireData(params.quest.agency, 3, :)))...
    );

results.full_offset.agency = comparisonResults;

plotQuestionnaires(...
    nanmean(squeeze(QuestionnaireData(params.quest.agency, 1, :))), ...
    nanmean(squeeze(QuestionnaireData(params.quest.agency, 3, :))), ...
    'Sense of Agency', params.conditions{1, 1}, params.conditions{1, 3}, ...
    comparisonResults.stats);


%%
results.detached_offset.Condition1 = params.conditions{1, 4};
results.detached_offset.Condition2 = params.conditions{1, 6};

[comparisonResults] = statisticsQuestionnaires (...
    nanmean(squeeze(QuestionnaireData(params.quest.ownership, 4, :))), ...
    nanmean(squeeze(QuestionnaireData(params.quest.ownership, 6, :)))...
    );

results.detached_offset.ownership = comparisonResults;

plotQuestionnaires(...
    nanmean(squeeze(QuestionnaireData(params.quest.ownership, 4, :))), ...
    nanmean(squeeze(QuestionnaireData(params.quest.ownership, 6, :))), ...
    'Sense of Ownership', params.conditions{1, 4}, params.conditions{1, 6}, ...
    comparisonResults.stats);

%%
[comparisonResults] = statisticsQuestionnaires (...
    nanmean(squeeze(QuestionnaireData(params.quest.agency, 4, :))), ...
    nanmean(squeeze(QuestionnaireData(params.quest.agency, 6, :)))...
    );

results.detached_offset.agency = comparisonResults;

plotQuestionnaires(...
    nanmean(squeeze(QuestionnaireData(params.quest.agency, 4, :))), ...
    nanmean(squeeze(QuestionnaireData(params.quest.agency, 6, :))), ...
    'Sense of Agency', params.conditions{1, 4}, params.conditions{1, 6}, ...
    comparisonResults.stats);


%%
results.nooffset_detached.Condition1 = params.conditions{1, 1};
results.nooffset_detached.Condition2 = params.conditions{1, 4};

[comparisonResults] = statisticsQuestionnaires (...
    nanmean(squeeze(QuestionnaireData(params.quest.ownership, 1, :))), ...
    nanmean(squeeze(QuestionnaireData(params.quest.ownership, 4, :)))...
    );

results.nooffset_detached.ownership = comparisonResults;

plotQuestionnaires(...
    nanmean(squeeze(QuestionnaireData(params.quest.ownership, 1, :))), ...
    nanmean(squeeze(QuestionnaireData(params.quest.ownership, 4, :))), ...
    'Sense of Ownership', params.conditions{1, 1}, params.conditions{1, 4}, ...
    comparisonResults.stats);

%%
[comparisonResults] = statisticsQuestionnaires (...
    nanmean(squeeze(QuestionnaireData(params.quest.agency, 1, :))), ...
    nanmean(squeeze(QuestionnaireData(params.quest.agency, 4, :)))...
    );

results.nooffset_detached.agency = comparisonResults;

plotQuestionnaires(...
    nanmean(squeeze(QuestionnaireData(params.quest.agency, 1, :))), ...
    nanmean(squeeze(QuestionnaireData(params.quest.agency, 4, :))), ...
    'Sense of Agency', params.conditions{1, 1}, params.conditions{1, 4}, ...
    comparisonResults.stats);


%%
results.offset_detached.Condition1 = params.conditions{1, 3};
results.offset_detached.Condition2 = params.conditions{1, 6};

[comparisonResults] = statisticsQuestionnaires (...
    nanmean(squeeze(QuestionnaireData(params.quest.ownership, 3, :))), ...
    nanmean(squeeze(QuestionnaireData(params.quest.ownership, 6, :)))...
    );

results.offset_detached.ownership = comparisonResults;

plotQuestionnaires(...
    nanmean(squeeze(QuestionnaireData(params.quest.ownership, 3, :))), ...
    nanmean(squeeze(QuestionnaireData(params.quest.ownership, 6, :))), ...
    'Sense of Ownership', params.conditions{1, 3}, params.conditions{1, 6}, ...
    comparisonResults.stats);

%%
[comparisonResults] = statisticsQuestionnaires (...
    nanmean(squeeze(QuestionnaireData(params.quest.agency, 3, :))), ...
    nanmean(squeeze(QuestionnaireData(params.quest.agency, 6, :)))...
    );

results.offset_detached.agency = comparisonResults;

plotQuestionnaires(...
    nanmean(squeeze(QuestionnaireData(params.quest.agency, 3, :))), ...
    nanmean(squeeze(QuestionnaireData(params.quest.agency, 6, :))), ...
    'Sense of Agency', params.conditions{1, 3}, params.conditions{1, 6}, ...
    comparisonResults.stats);


% % %% Save Variables
% % save('E:\GitHub\analysis-VR\data\03. Experiment_Rep\ProcessedData_Questionnaires.mat', ...
% %     'results');
% %
