function [] = doEverything (i_fig, data1, data2, cond1, ...
    cond2, FigTitle)

[mn, md, pttest, pmann, ~, ~] = ...
    analysisQuestions (data1, data2);

[fig1, fig2] = plotQuestionnaires(...
    data1, data2, ...
    FigTitle, ...
    cond1, cond2, pmann);

% Distributions
[~, pks2] = kstest2(data1(:), data2(:));

% Correlations
[R, P] = corrcoef (nanmean(data1), nanmean(data2));

[fig3] = plotCorrelations(data1, data2, ...
    FigTitle, cond1, cond2, ...
    R(1,2), P(1,2))

[pGroups] = analysisGroups(data1,data2);

FigName = strcat('Figure',num2str(i_fig));

saveas(fig1, ...
    strcat('C:\Users\User\Desktop\FiguresResubmission_MATLAB\', ...
    FigName, 'A.png'));
saveas(fig2, ...
    strcat('C:\Users\User\Desktop\FiguresResubmission_MATLAB\', ...
    FigName, 'B.png'));
saveas(fig3, ...
    strcat('C:\Users\User\Desktop\FiguresResubmission_MATLAB\', ...
    FigName, 'C.png'));

end 