questOwnership = 1:4;

iterations = 10000;

% get from questionnaires
addpath('getData\');
[q_static, q_dynamic] = get_questionnaire_data();

% static
addpath('statistics\');
pv = stat_bootstrapping(iterations, ...
    mean(squeeze(q_static(questOwnership, 2, :))), ...
    mean(squeeze(q_static(questOwnership, 1, :))));

% dynamic
pv_2 = stat_bootstrapping(iterations, ...
    reshape((squeeze(q_dynamic(questOwnership, 2, :))), 1, 48), ...
    reshape((squeeze(q_dynamic(questOwnership, 1, :))), 1, 48));
pv_3 = stat_bootstrapping(iterations, ...
    reshape((squeeze(q_dynamic(questOwnership, 3, :))), 1, 48), ...
    reshape((squeeze(q_dynamic(questOwnership, 1, :))), 1, 48));
pv_4 = stat_bootstrapping(iterations, ...
    reshape((squeeze(q_dynamic(questOwnership, 4, :))), 1, 48), ...
    reshape((squeeze(q_dynamic(questOwnership, 1, :))), 1, 48));
pv_5 = stat_bootstrapping(iterations, ...
    reshape((squeeze(q_dynamic(questOwnership, 5, :))), 1, 48), ...
    reshape((squeeze(q_dynamic(questOwnership, 1, :))), 1, 48));
pv_6 = stat_bootstrapping(iterations, ...
    reshape((squeeze(q_dynamic(questOwnership, 1, :))), 1, 48), ...
    reshape((squeeze(q_dynamic(questOwnership, 6, :))), 1, 48));
pv_7 = stat_bootstrapping(iterations, ...
    reshape((squeeze(q_dynamic(questOwnership, 1, :))), 1, 48), ...
    reshape((squeeze(q_dynamic(questOwnership, 7, :))), 1, 48));
pv_8 = stat_bootstrapping(iterations, ...
    reshape((squeeze(q_dynamic(questOwnership, 3, :))), 1, 48), ...
    reshape((squeeze(q_dynamic(questOwnership, 4, :))), 1, 48));