%%
addpath('extractData');
addpath('figures');
addpath('analyzeData/questionnaires');

%% Find variables 
% This file should be modified with the parameters of each experiment
[params] = GetParameters();


%% Extract Raw Data
[subjectData] = extractSociodemographics (params, 'sociodemographics.txt');

[questionnaireData.preprocessed] = extractQuestionnaires(params, subjectData);

save(strcat(params.dataDirectory, '\Results\subjectData'), 'subjectData');
save(strcat(params.dataDirectory, '\Results\preprocessedQuestionnaires.mat'), ...
    'questionnaireData');

%% Process Data
questionnaireData.processed.owner.visuomotor = ...
    squeeze(nanmean(squeeze(questionnaireData.preprocessed.visuomotorInformation.orderedResponses(params.quest.owner, :, :))));
questionnaireData.processed.ownerC.visuomotor = ...
    squeeze(nanmean(squeeze(questionnaireData.preprocessed.visuomotorInformation.orderedResponses(params.quest.ownerCnt, :, :))));
questionnaireData.processed.owner.outcome = ...
    squeeze(nanmean(squeeze(questionnaireData.preprocessed.outcomeOwnership.orderedResponses(params.quest.owner, :, :))));
questionnaireData.processed.ownerC.outcome = ...
    squeeze(nanmean(squeeze(questionnaireData.preprocessed.outcomeOwnership.orderedResponses(params.quest.ownerCnt, :, :))));

questionnaireData.processed.agency.visuomotor = ...
    squeeze(nanmean(squeeze(questionnaireData.preprocessed.visuomotorInformation.orderedResponses(params.quest.agenAction, :, :))));
questionnaireData.processed.agencyC.visuomotor = ...
    squeeze(nanmean(squeeze(questionnaireData.preprocessed.visuomotorInformation.orderedResponses(params.quest.agenActionCnt, :, :))));
questionnaireData.processed.agency.outcome = ...
    squeeze(nanmean(squeeze(questionnaireData.preprocessed.outcomeOwnership.orderedResponses(params.quest.agenAction, :, :))));
questionnaireData.processed.agencyC.outcome = ...
    squeeze(nanmean(squeeze(questionnaireData.preprocessed.outcomeOwnership.orderedResponses(params.quest.agenActionCnt, :, :))));

questionnaireData.processed.outcome.visuomotor = ...
    squeeze(nanmean(squeeze(questionnaireData.preprocessed.visuomotorInformation.orderedResponses(params.quest.agenOutcome, :, :))));
questionnaireData.processed.outcomeC.visuomotor = ...
    squeeze(nanmean(squeeze(questionnaireData.preprocessed.visuomotorInformation.orderedResponses(params.quest.agenOutcomeCnt, :, :))));
questionnaireData.processed.outcome.outcome = ...
    squeeze(nanmean(squeeze(questionnaireData.preprocessed.outcomeOwnership.orderedResponses(params.quest.agenOutcome, :, :))));
questionnaireData.processed.outcomeC.outcome = ...
    squeeze(nanmean(squeeze(questionnaireData.preprocessed.outcomeOwnership.orderedResponses(params.quest.agenOutcomeCnt, :, :))));

questionnaireData.processed.similarity.visuomotor = ...
    squeeze(nanmean(squeeze(questionnaireData.preprocessed.visuomotorInformation.orderedResponses(params.quest.similar, :, :))));
questionnaireData.processed.similarity.outcome = ...
    squeeze(nanmean(squeeze(questionnaireData.preprocessed.outcomeOwnership.orderedResponses(params.quest.similar, :, :))));

questionnaireData.processed.location.visuomotor = ...
    squeeze(nanmean(squeeze(questionnaireData.preprocessed.visuomotorInformation.orderedResponses(params.quest.location, :, :))));
questionnaireData.processed.location.outcome = ...
    squeeze(nanmean(squeeze(questionnaireData.preprocessed.outcomeOwnership.orderedResponses(params.quest.location, :, :))));


save(strcat(params.dataDirectory, '\Results\preprocessedQuestionnaires.mat'), ...
    'questionnaireData');

%% 


% mean, medians, std, and normality distribution. 
questionnaireData.results.ownership.visuomotor = ...
    data_results(questionnaireData.processed.owner.visuomotor); 

questionnaireData.results.ownership.outcome = ...
    data_results(questionnaireData.processed.owner.outcome);

questionnaireData.results.agency.visuomotor = ...
    data_results(questionnaireData.processed.agency.visuomotor);

questionnaireData.results.agency.outcome = ...
    data_results(questionnaireData.processed.agency.outcome);

questionnaireData.results.outcome.visuomotor = ...
    data_results(questionnaireData.processed.outcome.visuomotor);

questionnaireData.results.outcome.outcome = ...
    data_results(questionnaireData.processed.outcome.outcome);


% Friedman



% Control Statements
[questionnaireData.results.control_statements] = ...
    controlStatements(questionnaireData.processed);

% Pairwise 
[questionnaireData.results.pairwise] = ... 
    pairwiseComparisons (questionnaireData.processed);


% Correlation between the differences

% [results.correlations.aCIM] =  correlationDifference(...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.owner, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.owner, 2, :))), ...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.agenAction, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.agenAction, 2, :))));
% 
% [results.correlations.aCIO] =  correlationDifference(...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.owner, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.owner, 3, :))), ...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.agenAction, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.agenAction, 3, :))));
% 
% [results.correlations.aCIB] =  correlationDifference(...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.owner, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.owner, 4, :))), ...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.agenAction, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.agenAction, 4, :))));
% 
% 
% [results.correlations.oCIM] =  correlationDifference(...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.owner, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.owner, 2, :))), ...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.agenOutcome, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.agenOutcome, 2, :))));
% 
% [results.correlations.oCIO] =  correlationDifference(...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.owner, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.owner, 3, :))), ...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.agenOutcome, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.agenOutcome, 3, :))));
% 
% [results.correlations.oCIB] =  correlationDifference(...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.owner, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.owner, 4, :))), ...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.agenOutcome, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.visuomotorInformation.responses(params.quest.agenOutcome, 4, :))));
% 
% 
% 
% 
% [results.correlations.zCIM] =  correlationDifference(...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.owner, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.owner, 2, :))), ...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.agenAction, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.agenAction, 2, :))));
% 
% [results.correlations.zCIO] =  correlationDifference(...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.owner, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.owner, 3, :))), ...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.agenAction, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.agenAction, 3, :))));
% 
% [results.correlations.zCIB] =  correlationDifference(...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.owner, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.owner, 4, :))), ...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.agenAction, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.agenAction, 4, :))));
% 
% 
% [results.correlations.xCIM] =  correlationDifference(...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.owner, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.owner, 2, :))), ...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.agenOutcome, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.agenOutcome, 2, :))));
% 
% [results.correlations.xCIO] =  correlationDifference(...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.owner, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.owner, 3, :))), ...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.agenOutcome, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.agenOutcome, 3, :))));
% 
% [results.correlations.xCIB] =  correlationDifference(...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.owner, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.owner, 4, :))), ...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.agenOutcome, 1, :))) - ...
%     nanmean(squeeze(QuestionnaireData.outcomeOwnership.responses(params.quest.agenOutcome, 4, :))));
% 
% 
% 


save(strcat(params.dataDirectory, '\Results\preprocessedQuestionnaires.mat'), ...
    'questionnaireData');
%% Plot

load(strcat(params.dataDirectory, '\Results\preprocessedQuestionnaires.mat'));


fig1 = figure(1);
set(fig1, 'units', 'centimeters', 'position', [5 5 10.0 15.0]);
plotBoxplots(questionnaireData.processed.owner.visuomotor, ...
    'Visuomotor Information - Sense of ownership');









