function [results] = controlStatements (data)

% visuomotor sense of ownership
[results.ownership.visuomotor.congruent] = signrank (...
    data.owner.visuomotor(1, :), data.ownerC.visuomotor(1, :));
[results.ownership.visuomotor.incongruent_movement] = signrank (...
    data.owner.visuomotor(2, :), data.ownerC.visuomotor(2, :));
[results.ownership.visuomotor.incongruent_outcome] = signrank (...
    data.owner.visuomotor(3, :), data.ownerC.visuomotor(3, :));
[results.ownership.visuomotor.incongruent] = signrank (...
    data.owner.visuomotor(4, :), data.ownerC.visuomotor(4, :));

[results.ownership.outcome.control] = signrank (...
    data.owner.outcome(1, :), data.ownerC.outcome(1, :));
[results.ownership.outcome.detached_hand] = signrank (...
    data.owner.outcome(1, :), data.ownerC.outcome(1, :));
[results.ownership.outcome.incongruent_outcome] = signrank (...
    data.owner.outcome(1, :), data.ownerC.outcome(1, :));
[results.ownership.outcome.detached_hand] = signrank (...
    data.owner.outcome(1, :), data.ownerC.outcome(1, :));


[results.agency.visuomotor.congruent] = signrank (...
    data.agency.visuomotor(1, :), data.agencyC.visuomotor(1, :));
[results.agency.visuomotor.incongruent_movement] = signrank (...
    data.agency.visuomotor(2, :), data.agencyC.visuomotor(2, :));
[results.agency.visuomotor.incongruent_outcome] = signrank (...
    data.agency.visuomotor(3, :), data.agencyC.visuomotor(3, :));
[results.agency.visuomotor.incongruent] = signrank (...
    data.agency.visuomotor(4, :), data.agencyC.visuomotor(4, :));

[results.agency.outcome.control] = signrank (...
    data.agency.outcome(1, :), data.agencyC.outcome(1, :));
[results.agency.outcome.detached_hand] = signrank (...
    data.agency.outcome(1, :), data.agencyC.outcome(1, :));
[results.agency.outcome.incongruent_outcome] = signrank (...
    data.agency.outcome(1, :), data.agencyC.outcome(1, :));
[results.agency.outcome.detached_hand] = signrank (...
    data.agency.outcome(1, :), data.outcomeC.outcome(1, :));


[results.outcome.visuomotor.congruent] = signrank (...
    data.outcome.visuomotor(1, :), data.outcomeC.visuomotor(1, :));
[results.outcome.visuomotor.incongruent_movement] = signrank (...
    data.outcome.visuomotor(2, :), data.outcomeC.visuomotor(2, :));
[results.outcome.visuomotor.incongruent_outcome] = signrank (...
    data.outcome.visuomotor(3, :), data.outcomeC.visuomotor(3, :));
[results.outcome.visuomotor.incongruent] = signrank (...
    data.outcome.visuomotor(4, :), data.outcomeC.visuomotor(4, :));

[results.outcome.outcome.control] = signrank (...
    data.outcome.outcome(1, :), data.agencyC.outcome(1, :));
[results.outcome.outcome.detached_hand] = signrank (...
    data.outcome.outcome(1, :), data.outcomeC.outcome(1, :));
[results.outcome.outcome.incongruent_outcome] = signrank (...
    data.outcome.outcome(1, :), data.outcomeC.outcome(1, :));
[results.outcome.outcome.detached_hand] = signrank (...
    data.outcome.outcome(1, :), data.outcomeC.outcome(1, :));

end