function [questionnaireData, variables] = extractQuestionnaires(params, subjectData)

experimentType = '\Visuomotor Information\';
[questionnaireData.visuomotorInformation, ...
    variables.orderTrials.visuomotorInformation] = ...
    GetDataFromQuestionnaires(params.dataDirectory, ...
    experimentType, subjectData.subjectID);

experimentType = '\Outcome Ownership\';
[questionnaireData.outcomeOwnership, ...
    variables.orderTrials.outcomeOwnership] = ...
    GetDataFromQuestionnaires(params.dataDirectory, ...
    experimentType, subjectData.subjectID);

end