function [questionnaireData] = extractQuestionnaires(params, subjectData)

experimentType = '\Visuomotor Information\';
[questionnaireData.visuomotorInformation.orderedResponses, ...
    questionnaireData.visuomotorInformation.orderMatrix] = ...
    GetDataFromQuestionnaires(params.dataDirectory, ...
    experimentType, subjectData.subjectID);

experimentType = '\Outcome Ownership\';
[questionnaireData.outcomeOwnership.orderedResponses, ...
    questionnaireData.visuomotorInformation.orderMatrix] = ...
    GetDataFromQuestionnaires(params.dataDirectory, ...
    experimentType, subjectData.subjectID);

end